-- MySQL Script generated by MySQL Workbench
-- Sun 23 Jul 2017 06:19:46 PM WAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mcq-database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mcq-database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mcq-database` ;
USE `mcq-database` ;

-- -----------------------------------------------------
-- Table `mcq-database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcq-database`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(60) NULL,
  `status` CHAR(10) NULL DEFAULT 'student',
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `lastsigned_in` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `session` VARCHAR(32) NULL,
  `password` VARCHAR(64) NULL,
  `permission` INT(11) NULL DEFAULT 0 ,
  `banned` TINYINT(1) NULL DEFAULT 0,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcq-database`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcq-database`.`quiz` (
<<<<<<< HEAD
  `id` INT(8) NOT NULL,
=======
  `id` INT(8) NOT NULL AUTO_INCREMENT,
>>>>>>> bcf019d4a6acc2600860477f20e5cd4e569ba2aa
  `uid` VARCHAR(45) NULL,
  `quid` VARCHAR(45) NULL,
  `title` VARCHAR(200) NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `time` INT(3) NULL,
  `start_date` VARCHAR(45) NULL,
  `instructions` TEXT(300) NULL,
  `closed` TINYINT(1) NULL DEFAULT 0,
  `result` CHAR(4) NULL DEFAULT 'mail',
  `student_count` INT(8) NULL DEFAULT 0,
  `show_qtn_marks` TINYINT(1) NULL DEFAULT 0,
  `total_marks` INT(4) NULL DEFAULT 0,
<<<<<<< HEAD
  `user_id` INT NOT NULL,
  `question_qtn_Id` INT(8) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `question_qtn_Id`),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `quid_UNIQUE` (`quid` ASC),
  INDEX `fk_quiz_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_quiz_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mcq-database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
=======
  `question_qtn_Id` INT(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `quid_UNIQUE` (`quid` ASC),
  INDEX `fk_quiz_user_idx` (`uid` ASC))
>>>>>>> bcf019d4a6acc2600860477f20e5cd4e569ba2aa
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcq-database`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcq-database`.`question` (
  `qtn_Id` INT(8) NOT NULL,
  `quid` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL DEFAULT 'radio',
  `text` TEXT(6000) NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `qtn_mark` INT(3) NULL,
  `quiz_id` INT(8) NOT NULL,
  `quiz_user_id` INT NOT NULL,
  `quiz_question_qtn_Id` INT(8) NOT NULL,
<<<<<<< HEAD
  PRIMARY KEY (`qtn_Id`, `quiz_id`, `quiz_user_id`, `quiz_question_qtn_Id`),
  INDEX `fk_question_quiz1_idx` (`quiz_id` ASC, `quiz_user_id` ASC, `quiz_question_qtn_Id` ASC),
  CONSTRAINT `fk_question_quiz1`
    FOREIGN KEY (`quiz_id` , `quiz_user_id` , `quiz_question_qtn_Id`)
    REFERENCES `mcq-database`.`quiz` (`id` , `user_id` , `question_qtn_Id`)
=======
  PRIMARY KEY (`qtn_id`),
  INDEX `fk_question_quiz1_idx` (`quiz_id` ASC, `quiz_user_id` ASC, `quiz_question_qtn_Id` ASC),
  CONSTRAINT `fk_question_quiz1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `mcq-database`.`quiz` (`id` )
>>>>>>> bcf019d4a6acc2600860477f20e5cd4e569ba2aa
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcq-database`.`question_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcq-database`.`question_options` (
  `id` INT(8) NOT NULL,
  `qtn_id:` INT(8) NULL,
  `text` TEXT(6000) NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `answer` TINYINT(1) NULL DEFAULT 0,
  `question_qtn_Id` INT(8) NOT NULL,
  `question_quiz_id` INT(8) NOT NULL,
  `question_quiz_user_id` INT NOT NULL,
  `question_quiz_question_qtn_Id` INT(8) NOT NULL,
<<<<<<< HEAD
  PRIMARY KEY (`id`, `question_qtn_Id`, `question_quiz_user_id`, `question_quiz_question_qtn_Id`, `question_quiz_id`),
  INDEX `fk_question_options_question1_idx` (`question_qtn_Id` ASC, `question_quiz_id` ASC, `question_quiz_user_id` ASC, `question_quiz_question_qtn_Id` ASC),
  CONSTRAINT `fk_question_options_question1`
    FOREIGN KEY (`question_qtn_Id` , `question_quiz_id` , `question_quiz_user_id` , `question_quiz_question_qtn_Id`)
    REFERENCES `mcq-database`.`question` (`qtn_Id` , `quiz_id` , `quiz_user_id` , `quiz_question_qtn_Id`)
=======
  PRIMARY KEY (`id`),
  INDEX `fk_question_options_question1_idx` (`question_qtn_Id` ASC, `question_quiz_id` ASC, `question_quiz_user_id` ASC, `question_quiz_question_qtn_Id` ASC),
  CONSTRAINT `fk_question_options_question1`
    FOREIGN KEY (`question_qtn_Id`)
    REFERENCES `mcq-database`.`question` (`qtn_Id` )
>>>>>>> bcf019d4a6acc2600860477f20e5cd4e569ba2aa
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcq-database`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcq-database`.`answer` (
  `Id` INT(8) NOT NULL AUTO_INCREMENT,
  `qnt_id` INT(8) NULL,
  `quid` VARCHAR(45) NULL,
  `option_ids` TEXT(6000) NULL,
  `quiz_id` INT(8) NOT NULL,
  `question_qtn_Id` INT(8) NOT NULL,
<<<<<<< HEAD
  PRIMARY KEY (`Id`, `question_qtn_Id`),
=======
  PRIMARY KEY (`id`),
>>>>>>> bcf019d4a6acc2600860477f20e5cd4e569ba2aa
  INDEX `fk_answer_quiz_idx` (`quiz_id` ASC),
  INDEX `fk_answer_question1_idx` (`question_qtn_Id` ASC),
  CONSTRAINT `fk_answer_quiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `mcq-database`.`quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_qtn_Id`)
    REFERENCES `mcq-database`.`question` (`qtn_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcq-database`.`answer_has_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcq-database`.`answer_has_answer` (
  `answer_Id` INT(8) NOT NULL,
  `answer_Id1` INT(8) NOT NULL,
<<<<<<< HEAD
  PRIMARY KEY (`answer_Id`, `answer_Id1`),
=======
  PRIMARY KEY (`answer_Id`),
>>>>>>> bcf019d4a6acc2600860477f20e5cd4e569ba2aa
  INDEX `fk_answer_has_answer_answer2_idx` (`answer_Id1` ASC),
  INDEX `fk_answer_has_answer_answer1_idx` (`answer_Id` ASC),
  CONSTRAINT `fk_answer_has_answer_answer1`
    FOREIGN KEY (`answer_Id`)
    REFERENCES `mcq-database`.`answer` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_has_answer_answer2`
    FOREIGN KEY (`answer_Id1`)
    REFERENCES `mcq-database`.`answer` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mcq-database` ;

-- -----------------------------------------------------
-- Placeholder table for view `mcq-database`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcq-database`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mcq-database`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcq-database`.`view1`;
USE `mcq-database`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
